que1.6
ashok-choudhary-0/Node1.1 pull request #7
Opened 2023-09-18 13:03 UTC by ashok-choudhary-0

2023-09-18 13:08 UTC, amrit56789 commented on controllers/userController.js
> +    const userData = await userModel.findAll({ limit: 10, offset: (page - 1) * 10 })
Why you use here limit 10 suppose If I want only 5 user of 1st page then what to do?

2023-09-18 13:13 UTC, amrit56789 commented on controllers/userController.js
> +const getAllUsersData = async (req, res) => {
we are find limit userdata so choose variable name carefully.

2023-09-19 06:12 UTC, amrit56789 commented on controllers/userController.js
> +  const limitValue = Number(req.query.limit || 10)
Limit also go in params

2023-09-19 08:00 UTC, meanstack9716 requested changes

2023-09-19 08:00 UTC, meanstack9716 commented on controllers/userController.js
> +  const page = req.params.page
you should also parse/number the page param as well as @ashok-choudhary-0

2023-09-19 08:00 UTC, meanstack9716 commented on controllers/userController.js
> +      res.status(500).send({ message: "oops data not found" })
do not send 500 status without error, 500 is for there is some issue in code, that server can't handle.
So this response will also be 200 with count 0 and user data blank array @ashok-choudhary-0

2023-09-19 08:42 UTC, merged